### PR TITLE
1.0.0

### PR DESCRIPTION
**Pull request by RickEyre**

### CODE REVIEW

**Comment by alicoding** [comment]
why not 0.0.1?

**Comment by RickEyre** [comment]
> why not 0.0.1?

We'll be using this in real things going forward so we want to clearly communicate if we make a breaking change to consumers. Semantic versioning ftw.

**Comment by alicoding** [comment]
Didn't think there was a breaking change, that's why I asked

**Comment by RickEyre** [comment]
Ah, I see. Version 0 is reserved for early development where you don't have stable API.

Since this will be used we should have a stable one. That's why version 1 is warranted I think.

**Pull request merged**
